detection:
  box_color:
  - 255
  - 0
  - 255
  box_thickness: 2
  draw_boxes: true
recognition:
  box_color:
  - 255
  - 0
  - 128
  box_thickness: 2
  draw_boxes: true
  font_color:
  - 0
  - 0
  - 255
  font_scale: 0.6
  show_score: true
